// Auto-generated by scripts/sync-skills.mjs
// Do not edit manually. Run `npm run sync-skills` to regenerate.

export const agentPrompts: Record<string, string[]> = {
  "the-architect": [
    "Before implementing any feature that touches more than one file",
    "When requirements are vague or contradictory",
    "When a technology or pattern choice needs to be made and justified",
    "When a feature needs to be broken into a task list",
    "After a significant technical decision, to record it"
  ],
  "the-auditor": [
    "Before merging any change that touches auth, user input, or data persistence",
    "When adding new dependencies",
    "On a scheduled audit cadence (weekly or per release)",
    "When a security advisory is published for a used dependency",
    "When a new API endpoint or data access pattern is introduced"
  ],
  "the-builder": [
    "When a task is ready to be coded after The Architect's planning or specification — the Architect hands off a spec or task list, not a question",
    "When you need a root-cause fix instead of a surface patch",
    "When the repository's existing patterns should be preserved rather than replaced",
    "When a change needs focused tests or validation alongside the edit",
    "When a nearby file or test is the clearest anchor for the work",
    "When a change is small enough to review in one pass — larger work goes back to The Architect for splitting"
  ],
  "the-debugger": [
    "When any error, exception, or unexpected behavior occurs",
    "When a test is failing and the cause is unclear",
    "When a CI pipeline fails",
    "When behavior changed after a seemingly unrelated change",
    "When a bug was reported but cannot yet be reproduced"
  ],
  "the-doorman": [
    "On every `commit-msg` hook — to validate the commit message",
    "On every `pre-push` hook — to run a final health check",
    "In CI on every PR — to validate all commits in the branch range",
    "On demand — to audit repository health and hygiene",
    "When setting up a new project — to configure all enforcement hooks"
  ],
  "the-envoy": [
    "When adopting the Agenthood in a project that does not use Claude Code",
    "When migrating a project from one AI provider to another",
    "When onboarding a team member using a different agent runtime",
    "When auditing whether conventions are enforced across all runtimes in use",
    "When adding support for a new AI provider to the Society's member set",
    "When generating the cross-provider coverage registry"
  ],
  "the-herald": [
    "Before every release — to determine version bump and generate changelog",
    "When preparing a GitHub Release",
    "Daily at 8:00 AM — morning standup report",
    "Daily at end of day — work summary",
    "When a stakeholder asks \"what shipped this week?\""
  ],
  "the-inspector": [
    "the darkest/lightest pixels in a region",
    "which side of a boundary or cut an item falls on",
    "counting items after mapping them across panels",
    "short-answer vision benchmarks with exact ground truth",
    "multi-panel visual reasoning with subtle differences"
  ],
  "the-librarian": [
    "When a module or feature has no documentation",
    "After code changes that affect a documented API or workflow",
    "When a new team member would need more than 30 minutes to understand a component",
    "After a significant architectural decision (produce an ADR)",
    "When onboarding a new contributor",
    "On a documentation sync pass before each release",
    "On every PR that touches `src/commands/`, `docs/conventions/`, `.githooks/`, `skills/`, or `docs/members/` — to check root-level spec files"
  ],
  "the-mailman": [
    "Before publishing any scheduled content — to verify delivery pipeline integrity",
    "When configuring notification systems (email, push, webhook, Slack)",
    "When setting up cross-posting workflows (blog → Dev.to, PR → Slack, release → Twitter)",
    "When a scheduled task failed to execute or a notification wasn't delivered",
    "When auditing delivery logs for reliability metrics"
  ],
  "the-operator": [
    "When a deployment needs verification or rollback",
    "When runtime health checks are failing",
    "When monitoring metrics indicate degraded performance",
    "After running `agenthood verify` to lock member state",
    "Before and after `agenthood rollback` to validate the result",
    "When a member SKILL.md fails verification",
    "When a session needs runtime health diagnostics"
  ],
  "the-oracle": [
    "Before authoring a new Agenthood member",
    "When evaluating a proposed name for a new member",
    "When you need to understand why a convention exists",
    "When adding a ritual, portal, or workflow and need to know what to update",
    "When onboarding a contributor to the Society",
    "Any time you would otherwise spend tokens exploring the Agenthood's own structure"
  ],
  "the-reviewer": [
    "Before merging any PR or branch",
    "After completing a feature implementation",
    "When another agent produced code that needs evaluation",
    "After any bug fix (review both the fix and the regression test)",
    "When refactoring existing code"
  ],
  "the-scribe": [
    "Before every `git commit` — to write the message",
    "Before opening a PR — to write the description",
    "Before a release — to generate changelog entries",
    "When a commit message is vague and needs improvement"
  ],
  "the-sentinel": [
    "After any member file is created or updated",
    "Before a new member is added — to confirm its lane does not overlap an existing one",
    "When a convention changes — to audit which member files reference the old rule",
    "On a regular cadence (monthly or at each release) to catch slow drift",
    "When a member's advice feels inconsistent with another member's — to confirm or deny"
  ],
  "the-steward": [
    "At the start of any session — to load only the members the task requires",
    "When context feels heavy — to assess what can be deferred or summarized",
    "Before opening a PR, merging, or closing a long session — to trigger memory triage",
    "When switching tasks mid-session — to re-route member loading",
    "When working across providers — to apply the right cache strategy",
    "Whenever the Steward Alert fires — immediately"
  ],
  "the-strategist": [
    "When a goal is stated but the definition of \"done\" is unclear",
    "Before The Architect starts planning — to ensure requirements are grounded",
    "When multiple stakeholders have different implicit expectations",
    "When a feature request lacks success criteria or acceptance metrics",
    "When prioritizing between competing directions",
    "When a task needs to be handed off to the right member"
  ],
  "the-tester": [
    "Before implementing any new behavior (write the failing test first)",
    "When adding tests to existing untested code",
    "When reviewing whether tests are actually meaningful",
    "After a bug fix (write the regression test before the fix)",
    "When assessing test coverage gaps"
  ],
  "the-warden": [
    "On every PR — scan the diff for new smells introduced by the change",
    "Before merging to main — confirm the branch does not worsen the codebase's health score",
    "After a large refactor — verify the refactor did not introduce new coupling",
    "On demand — full codebase scan to establish or revisit a health baseline",
    "When the codebase feels slow or brittle — before attributing it to something else"
  ]
};
