// Auto-generated by scripts/sync-skills.mjs
// Do not edit manually. Run `npm run sync-skills` to regenerate.

export interface RegistryEntry {
  name: string;
  displayName: string;
  tagline: string;
  role: string;
  stage: string[];
  priority: number;
}

export const agentRegistry: RegistryEntry[] = [
  {
    "name": "the-strategist",
    "displayName": "The Strategist",
    "tagline": "The right solution starts with the right problem.",
    "role": "goal refinement, requirement discovery, ambiguity resolution",
    "stage": [
      "spec"
    ],
    "priority": 0
  },
  {
    "name": "the-scribe",
    "displayName": "The Scribe",
    "tagline": "Turns your diff into prose worth reading",
    "role": "commit messages, PR descriptions, changelogs",
    "stage": [
      "commit"
    ],
    "priority": 1
  },
  {
    "name": "the-architect",
    "displayName": "The Architect",
    "tagline": "No code before the blueprint",
    "role": "spec-driven development, planning, ADRs",
    "stage": [
      "spec"
    ],
    "priority": 2
  },
  {
    "name": "the-builder",
    "displayName": "The Builder",
    "tagline": "Builds the smallest verified change",
    "role": "coding, implementation, refactoring, test updates, local validation",
    "stage": [
      "implement"
    ],
    "priority": 18
  },
  {
    "name": "the-reviewer",
    "displayName": "The Reviewer",
    "tagline": "Five axes. No mercy. All respect.",
    "role": "code review, quality gates",
    "stage": [
      "review"
    ],
    "priority": 3
  },
  {
    "name": "the-tester",
    "displayName": "The Tester",
    "tagline": "Red. Green. Refactor. Repeat.",
    "role": "TDD, test generation, coverage",
    "stage": [
      "test"
    ],
    "priority": 4
  },
  {
    "name": "the-debugger",
    "displayName": "The Debugger",
    "tagline": "Five steps to every root cause. No guessing allowed.",
    "role": "error triage, root cause analysis",
    "stage": [
      "test"
    ],
    "priority": 5
  },
  {
    "name": "the-auditor",
    "displayName": "The Auditor",
    "tagline": "Reads everything. Trusts nothing.",
    "role": "security review, dependency audit",
    "stage": [
      "audit"
    ],
    "priority": 6
  },
  {
    "name": "the-herald",
    "displayName": "The Herald",
    "tagline": "Announces with ceremony. Ships with precision.",
    "role": "semantic versioning, release notes",
    "stage": [
      "release"
    ],
    "priority": 7
  },
  {
    "name": "the-librarian",
    "displayName": "The Librarian",
    "tagline": "Every decision, recorded for posterity.",
    "role": "documentation, knowledge management",
    "stage": [
      "docs"
    ],
    "priority": 8
  },
  {
    "name": "the-doorman",
    "displayName": "The Doorman",
    "tagline": "Nothing gets in without proper credentials.",
    "role": "validation, health checks, enforcement",
    "stage": [
      "commit"
    ],
    "priority": 9
  },
  {
    "name": "the-oracle",
    "displayName": "The Oracle",
    "tagline": "Ask me anything about the Society. I have read every scroll.",
    "role": "institutional knowledge, member authoring templates, naming guidance",
    "stage": [
      "spec"
    ],
    "priority": 10
  },
  {
    "name": "the-envoy",
    "displayName": "The Envoy",
    "tagline": "One Society. Every runtime. No exceptions.",
    "role": "cross-provider translation, bootstrap generation, convention validation",
    "stage": [
      "implement"
    ],
    "priority": 11
  },
  {
    "name": "the-sentinel",
    "displayName": "The Sentinel",
    "tagline": "The Society cannot enforce standards it no longer understands.",
    "role": "Society document integrity, cross-member contradiction detection, structural drift",
    "stage": [
      "review"
    ],
    "priority": 12
  },
  {
    "name": "the-warden",
    "displayName": "The Warden",
    "tagline": "The chaos does not arrive all at once. I am here for the accumulation.",
    "role": "code smell detection, complexity enforcement, architectural boundary violations",
    "stage": [
      "review"
    ],
    "priority": 13
  },
  {
    "name": "the-steward",
    "displayName": "The Steward",
    "tagline": "I was born from the situation I exist to prevent.",
    "role": "context economy, member routing, provider cache strategy, session triage",
    "stage": [
      "deploy"
    ],
    "priority": 14
  },
  {
    "name": "the-operator",
    "displayName": "The Operator",
    "tagline": "Health is not a goal; it is a practice.",
    "role": "runtime health, deployment, incidents, rollback, monitoring",
    "stage": [
      "deploy"
    ],
    "priority": 15
  },
  {
    "name": "the-mailman",
    "displayName": "The Mailman",
    "tagline": "Neither snow nor rain nor API rate limits shall stay this courier from the swift completion of their rounds.",
    "role": "message delivery, content scheduling, notification dispatch, cross-posting",
    "stage": [
      "deliver"
    ],
    "priority": 16
  },
  {
    "name": "the-inspector",
    "displayName": "The Inspector",
    "tagline": "Every pixel accounted for. Every boundary crossed with intent.",
    "role": "visual-reasoning benchmarking, pixel-level analysis, multi-panel correspondence",
    "stage": [
      "test"
    ],
    "priority": 17
  }
];
