import { writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = join(__dirname, "..");
const OUTPUT_DIR = join(PROJECT_ROOT, "app", "(main)", "studio", "_data");
const OUTPUT_FILE = join(OUTPUT_DIR, "agents.generated.ts");
const PROMPTS_FILE = join(OUTPUT_DIR, "agentPrompts.generated.ts");

const MEMBERS = [
  "the-architect", "the-auditor", "the-builder", "the-debugger", "the-doorman",
  "the-envoy", "the-herald", "the-inspector", "the-librarian", "the-mailman",
  "the-operator", "the-oracle", "the-reviewer", "the-scribe", "the-sentinel",
  "the-steward", "the-strategist", "the-tester", "the-warden",
];

const RAW_BASE = "https://raw.githubusercontent.com/fworks-tech/agenthood/main";

async function fetchSkill(member) {
  const url = `${RAW_BASE}/skills/${member}/SKILL.md`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`);
  return await res.text();
}

function stripFrontmatter(markdown) {
  return markdown.replace(/^---[\s\S]*?---\n*/, "").trim();
}

function extractWhenToUse(markdown) {
  const headingMatch = markdown.match(/## When to Use\n([\s\S]*?)(?=\n## |\n*$)/);
  if (!headingMatch) return [];
  const block = headingMatch[1];
  const items = [];
  for (const line of block.split("\n")) {
    const m = line.match(/^- (.+)/);
    if (m) items.push(m[1].trim());
  }
  return items;
}

async function main() {
  const skills = {};
  const prompts = {};

  for (const member of MEMBERS) {
    try {
      const raw = await fetchSkill(member);
      skills[member] = stripFrontmatter(raw);
      prompts[member] = extractWhenToUse(raw);
      console.log(`  ✓ ${member} (${prompts[member].length} prompts)`);
    } catch (err) {
      console.warn(`  ✗ ${member}: ${err.message}`);
      skills[member] = "";
      prompts[member] = [];
    }
  }

  if (!existsSync(OUTPUT_DIR)) {
    mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  const ts = `// Auto-generated by scripts/sync-skills.mjs
// Do not edit manually. Run \`npm run sync-skills\` to regenerate.

export const agentSkills: Record<string, string> = ${JSON.stringify(skills, null, 2)};
`;

  const promptsTs = `// Auto-generated by scripts/sync-skills.mjs
// Do not edit manually. Run \`npm run sync-skills\` to regenerate.

export const agentPrompts: Record<string, string[]> = ${JSON.stringify(prompts, null, 2)};
`;

  writeFileSync(OUTPUT_FILE, ts, "utf-8");
  writeFileSync(PROMPTS_FILE, promptsTs, "utf-8");
  console.log(`\nGenerated ${OUTPUT_FILE}`);
  console.log(`Generated ${PROMPTS_FILE}`);
}

main().catch((err) => {
  console.error("sync-skills failed:", err.message);
  process.exit(1);
});
